server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;
    client_max_body_size 6M;

    # Frontend
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Backend API routing
    location /api/ {
        root /var/www/backend/public;
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Laravel PHP FastCGI
    location ~ \.php$ {
        root /var/www/backend/public;
        fastcgi_pass ocas-php-fpm-1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    # Socket.io routing
    location /socket.io/ {
        proxy_pass http://ocas-node-1:3001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }
}
